### ISSUE TITLE
[토비의 스프링] 5.4.4 테스트 오브젝트가 간접적으로 넘기는 값과 행위의 검증의 의미

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#105]
제목그대로입니다.
394p 위에서 3번째 문단입니다.

의존 오브젝트에 넘기는 값과 행위를 검증하고 싶다면,
더 좁은 관심사의 테스트를 새로 생성하면 되는것이 아닐까요?
왜 UserService 테스트의 과정에 이러한 내용이 포함되어야 하는지 이해가 되지 않습니다.

**Comment by taxol1203** [comment]
대연님 말씀의 `더 좁은 관심사의 테스트`가 결국 UserServiceTest의 `MockMailSender`을 생성하고 이를 검증하는 것이 아닐까요?

만약 그래도 이해 안되시면, 토비의 스프링에서는 목 오브젝트의 활용을 소개하기 위해 억지로 끼워놓은? 내용 이라고 생각하시는 것이 나쁘지 않을 듯 합니다.
