### ISSUE TITLE
[토비의 스프링] 5.4.1_JavaMail 메일 발송 코드

### ISSUE THREAD

**Issue by taxol1203** [JavaBookStudy/JavaBook#106]
![wtf](https://user-images.githubusercontent.com/38308337/128602397-3aa6cf07-6c1f-4ae0-a7ae-d67f06e976d3.PNG)

옛날 코드라서 그런지, 위 빨간 줄이 쳐져있는 클래스들은 전부 import를 하지 못합니다.  

혹시 해결하신 분 있으신가요?

**Comment by taxol1203** [comment]
pom.xml의 `com.springsource.javax.activation`과 `com.springsource.javax.mail`도 마찬가지로 
`Missing artifact`입니다.

**Comment by kjsu0209** [comment]
```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
```
spring boot쓰시면 이걸로 해보세요 🤔
