### ISSUE TITLE
[토비의 스프링] 6.5.3 포인트컷 execution() 표현식의 함정

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#112]
500p에 언급된 타입패턴의 한계, 즉

* (*..*ServiceImpl.upgrade* (..))로 만든 표현식에 TestUserService 클래스의 빈이 선정되는 문제에 대하여,
상당히 직관적이지 않은 동작이라고 생각합니다.

간단한 프로젝트에선 문제가 되진 않겠지만, 프로젝트가 복잡해지고 수많은 클래스가 존재하게 된다면 원하는 클래스만을 지정하는 AspectJ 포인트컷 표현식을 작성하는데 문제가 생길 것 같습니다.

포인트컷 표현식을 염두하고 작명하는 규칙같은게 존재할까요?

**Comment by kjsu0209** [comment]
포인터컷 표현식을 염두하고 작명하는 규칙은 따로 없는 것 같지만, 자바 표준 명명 규칙에 따라 메서드 이름을 짓거나 자체 코드 컨벤션을 확실히 정의하면 충분히 포인트컷 표현식을 쓸 수 있을 것 같습니다.

**Comment by kjsu0209** [comment]
[링크](https://ozofweird.tistory.com/entry/Java-%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99)

자바 명명 규칙 정리글 공유드립니다
