### ISSUE TITLE
[토비의 스프링] 이슈 채우는 용도 겸 격리 수준에 대한 정리

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#115]
책에서는 트랜잭션 전파에 대해서는 설명을 잘 해놨지만
DB 격리수준에 대해서는 설명을 생략해놓아 별도로 공부한 내용을 전달드립니다.
팀 블로그를 참조하시길 바랍니다.
https://javabookstudy.github.io/%ED%86%A0%EB%B9%84%EC%9D%98_%EC%8A%A4%ED%94%84%EB%A7%81/TS-Chapter-6.6~6.7/

**Comment by taxol1203** [comment]
515p. 마지막에서 두번째 줄 내용이 이해가 안되어 질문을 하려했는데, 이 issue로 해결이 되겠네요! 감사합니다
```
따라서 적절하게 격리수준을 조정해서 가능한 많은 트랜잭션을 동시에 진행시키면서도 문제가 발생하지 않게 하는 제어가 필요하다.
```
