### ISSUE TITLE
[토비의 스프링] 6.6.1_조합된 트랜잭션 

### ISSUE THREAD

**Issue by taxol1203** [JavaBookStudy/JavaBook#116]
514p. PROPAGATION_REQUIRED 단락 내용 중,  
```
PROPAGATION_REQUIRED 트랜잭션 전파 속성을 갖는 코드는 다양한 방식으로 결합하여 하나의 트랜잭션으로 구성하기 쉽다.
Ex) A, B, A->B, B->A 와 같은 네 가지의 조합된 트랜잭션이 모두 가능하다.
```
이 있습니다.   

여기서 말하는 조합된 트랜잭션이란 것이 무엇인지 이해가 되질 않습니다.

**Comment by daebalprime** [comment]
말 그대로 트랜잭션의 가능한 조합의 경우의 수입니다.
A 단독으로 트랜잭션 내에서 처리하기,
A가 트랜잭션을 시작해서 B가 참여하고 모두 수행한 이후 트랜잭션 종료하기,
...
와 같은 의미입니다.
