### ISSUE TITLE
[토비의 스프링] 7.4.2_확장된 기능을 받는 DI

### ISSUE THREAD

**Issue by taxol1203** [JavaBookStudy/JavaBook#122]
622 p.의 마지막 문단에서,   
```
`BaseSqlService`는 초기화를 통한 SQL 등록과 조회만을 목적으로 SQL 레지스트리 오브젝트를 사용할 것이므로, 
기존의 SqlRegistry 인터페이스를 통해 접근하면 충분하다
```  
이 뜻은, 새로운 기능(메스드)을 확장한 interface `UpdatableSqlRegisry`가 아닌 기존의 `SqlRegistry`만 사용하면 된다고 되어있습니다.  

그런데, 그림 7-11을 보면, `SqlRegistry`를 구현한 클래스를 DI 받는 것이 아닌 `UpdatableSqlRegisry`를 구현한 `MyUpdatableSqlRegistry`를 DI를 받고있습니다.  
`UpdatableSqlRegisry`를 구현한 클래스이면, `BaseSqlService`의 관심사에 필요없는 기능(메서드)들이 있을 것인데 왜 이런 방식을 사용하였는지 궁금합니다.

**Comment by kjsu0209** [comment]
```BaseSqlService```는 ```SqlRegistry```를 구현하고 있고, ```MyUpdatableSqlRegitry```는 ```UpdatableSqlRegistry```를 구현하고 있으니, 각 클래스는 관심사에 따라 분리되어 있다고 볼 수 있습니다. 

질문하신 ```BaseSqlService```가 ```MyUpdatableSqlRegitry```를 DI 받는 건 관심사가 합쳐진다는 개념보다는 ```BaseSqlService```를 확장시킨다는 걸로 생각하면 될 것 같습니다. 관심사는 인터페이스를 통해 이미 분리되어 있으니까요.

결국 ```BaseSqlService```에서 ```MyUpdatableSqlRegitry```가 하는 일을 간접적으로 수행할 수 있어서 무슨 의미가 있나 싶지만, 결국 관심사의 분리를 통해 분리된 모듈을 ```SqlAdminService```에서 갖다 쓸 수 있게 됩니다.
