### ISSUE TITLE
[토비의 스프링] 1.1.3_com.mysql.cj.jdbc.Driver

### ISSUE THREAD

**Issue by kjsu0209** [JavaBookStudy/JavaBook#60]
1.1.3 예제 코드에서 mysql.jdbc.Driver 라이브러리를 사용하는데 실행시켜보니 deprecate되었고 mysql.cj.jdbc.Driver 쓰라고 나오네요.. 아래 경고 메시지만 한 줄 나오고 나머지 코드는 잘 실행돼요.

다른 분들도 이렇게 나오는지 궁금합니다 👀 

```
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.
```

**Comment by daebalprime** [comment]
SSAFY에서도 mysql.cj.jdbc.Driver로 프로젝트 많이 했었습니다..ㅎㅎ
