### ISSUE TITLE
[토비의 스프링] 궁금한거 없어서 올리는 Spring DI는 어떻게 작동할까?

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#62]
https://blog.woniper.net/336

들어가서 가벼운 마음으로 읽으시면 좋을 것 같아 공유드립니다.

**Comment by kjsu0209** [comment]
https://velog.io/@gillog/Spring-DIDependency-Injection-%EC%84%B8-%EA%B0%80%EC%A7%80-%EB%B0%A9%EB%B2%95

저도 공유 드립니다!

-----------------------
#### Spring에서 의존성을 주입하는 세 가지 방법
1. 필드 주입 (필드에 @Autowired)
2. 수정자 주입 (Setter method)
3. **생성자 주입** (생성자에 @Autowired)

=> 생성자 주입이 권장되는데, 그 이유는 필수적으로 사용해야 하는 의존성 없이는 인스턴스를 만들지 못하게 할 수 있기 때문.
=> Spring 4.3부터는 클래스 생성자가 하나고, 주입받는 객체가 Bean 등록이 되어 있다면 @Autowired 생략가능
