### ISSUE TITLE
토비의 스프링 관련은 아니고 Q&A 파일 관리 건의입니다.

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#67]
Q&A 파일을 주 별로 생성된 폴더에 별도로 관리하는 대신, 파일이름으로 몇 주차의 질문 목록인지 구분하여 하나의 폴더에 담는 것이 어떠할까 싶습니다.

**Comment by kjsu0209** [comment]
추후에 발표 자료 올리는 게 있을까 싶어서 그렇게 하긴 했는데
하나로 합치는게 더 낫겠네요,, 방금 2주차 폴더 만들고 2주차 qna도 올리면서 고민하긴 했었어요ㅋㅋㅋ
단톡에서 의견 취합하도록 하겠습니다 👍
