### ISSUE TITLE
[토비의 스프링] 읽어볼 만한 자료

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#72]
https://yaboong.github.io/spring/2019/08/29/why-field-injection-is-bad/

우리가 배웠던 필드 주입(@Autowired)가 나쁜 이유가 있었네요.
생성자 주입을 권장하는 이유에 대한 글이니 한 번쯤 읽어보시면 좋을 듯 합니다.

**Comment by kjsu0209** [comment]
간단히 요약 남깁니다.

필드 주입(@Autowired)는 간편하지만 컨테이너 외부에서 객체 주입을 할 수 없게 된다. 컨테이너 외부에서 단위 테스트를 할 수 없게 되며, 순환 참조가 일어나는지 발견할 수 있는 방법이 없다 . 

결론: 생성자 주입을 씁시다.
