### ISSUE TITLE
[토비의 스프링] 2.4.2_테스트 시 DAO가 사용할 DataSource 오브젝트를 바꿔주는 법 

### ISSUE THREAD

**Issue by jth2747** [JavaBookStudy/JavaBook#79]
책 191쪽부터 195쪽까지 입니다.
테스트를 위해 DataSource를 바꾸어주는 방법을 세 가지 정도 설명하고 있는데
이 방법들이 그냥 testdb라는 새로운 테이블을 하나 생성해서 테스트해보는 것과 비교해 어떤 명확한 장점이 있는 걸까요?
번거로움을 해결하는 것과 테스트 속도 정도의 장점일까요??

**Comment by taxol1203** [comment]
위 셋 방법 모두, 기존 서비스를 운영 중인 코드에서  테스트 db를 사용하기 위해 db connection을 변경하여 운영 DB와 테스트 DB를 분리하는 과정입니다.

따라서 testdb를 생성하여 테스트 하는것이 맞으며, testdb를 사용하기 위해 기존 코드에서 변경하는 방법과 그에 따른 장 단점을 소개하는 것입니다.
