### ISSUE TITLE
[토비의 스프링] JUnit4->JUnit5에서 바뀐 부분

### ISSUE THREAD

**Issue by kjsu0209** [JavaBookStudy/JavaBook#80]
지난주 Q&A에 넣었다가 뺀 질문인데 한번 정리해보면 좋을 것 같아 이슈 등록해봅니다,, 😸

**Comment by taxol1203** [comment]
1.	테스트 클래스와 메소드는 더이상 가시성(visibility)이 public으로 선언되지 않아도 동작합니다. 물론 기존과 같이 public으로 선언하거나 protected로 선언해도 동일하게 동작합니다.

2.	Assertion문 전체를 실행할 수 있는 기능이 추가되었습니다.   
이전버전에서는 Assertion에 실패할 경우 나머지 Assertion문이 실행되지 않았기때문에 전체를 성공시기키위해서는 여러 번 테스트를 수행하면서 코드를 수정해야 전체를 평가할 수 있게 됨으로서 단위 테스트 수행 횟수를 감소시킬 수 있을듯합니다

3.	테스트 메소드 내부에 제약시간안에 수행하도록 제약을 걸 수 있게 하였습니다.  
`assertTimeout`

4.	@DisplayName
IDE나 빌드 툴에서 표시할 테스트 이름을 지정하는 기능
