### ISSUE TITLE
[토비의 스프링] Spring Boot로 예제 연습 가능할까요?

### ISSUE THREAD

**Issue by kjsu0209** [JavaBookStudy/JavaBook#83]
인텔리제이 써본다고 하다가 스프링부트로 플젝 만들어서 예제 따라해 보고 있는데,
혹시 스프링부트로 예제 연습하고 계신 분 있으실까요?

초기 설정을 멋대로 해 놓아서 gradle에다 스프링부트로 예제 진행중입니다..

**Comment by daebalprime** [comment]
코드를 별도로 작성하고 있지는 않지만 설정만 잘 해놓으셨다면 스프링 부트와 스프링의 차이는 크지 않을 것이라 생각합니다.

**Comment by taxol1203** [comment]
전 sts 환경에서 스프링 부트로 사용하고 있습니다!
