### ISSUE TITLE
[토비의 스프링] 3.5.3_템플릿/콜백 예제

### ISSUE THREAD

**Issue by jth2747** [JavaBookStudy/JavaBook#84]
3.5.1에 템플릿/콜백 패턴는 템플릿의 작업 흐름 중 특정 기능을 위해 콜백이 한번 정도 호출되어서 사용되는 방식이라고 하는데, 
252~253쪽에서 3-34가 템플릿 코드고 3-35 코드에서 오히려 템플릿이 호출되는 구조가 아닌가요?
3-34와 3-35가 템플릿/콜백 패턴 개념 하에 어떤식으로 동작하는지 잘 이해가 가지 않습니다.

**Comment by taxol1203** [comment]
우선 `템플릿의 작업 흐름 중 특정 기능을 위해 콜백이 한번 정도 호출되어서 사용되는 방식`은 3-35에서, `BufferedReaderCallback`가 콜백함수입니다.  
따라서, `fileReadTemplate` 템플릿 메서드를 사용할 때 익명 클래스로 `BufferedReaderCallback` 콜백 메서드를 만들고 바로 호출하여 사용하는 것 입니다.

3-34에서 템플릿 메서드의 매개변수에 `BufferedReaderCallback`이 있는 이유가 이 때문입니다.
