### ISSUE TITLE
[토비의 스프링] 3.5.1 241p 컨텍스트의 여러 의미

### ISSUE THREAD

**Issue by daebalprime** [JavaBookStudy/JavaBook#85]
제가 알고 있는컨텍스트는 2가지 의미를 담고 있습니다.
1. 전략 패턴에서의 context
2. 컴퓨터공학에서 말하는 특정 코드가 실행되는 환경의 문맥 그 자체로 state에 가까운 의미

241p 아래서 4번째 줄을 보시면, '컨텍스트 정보를 전달받을 때 사용된다' 라고 말하는 부분은 2번째 의미일까요 아님 다른 의미일까요

**Comment by kjsu0209** [comment]
저는 ApplicationContext의 Context 개념으로 이해했는데 말씀하신 2번째 의미랑 비슷한 것 같네요!

**Comment by taxol1203** [comment]
해당 단원에서 템플릿 / 콜백 패턴 설명의 콜백 메서드 예제입니다.
```java
@Override
  public PreparedStatement makePreparedStatement(Connection c) throws SQLException {
  return c.prepareStatement(query);
 }
```
여기서 `컨텍스트 정보`는 콜백 인터페이스 메서드의 파라미터를 뜻하고 이는 `Connection c`인데,  
이 `Connection c`는 JdbcContext에서 DI 해주어 콜백에 넘겨주므로, 여기서 context는 `JdbcContext`를 뜻하는게 아닐까요?
