### ISSUE TITLE
[토비의 스프링] 3.6.2_queryForInt() 

### ISSUE THREAD

**Issue by jth2747** [JavaBookStudy/JavaBook#86]
스프링 3.2.2 이후로 queryForInt() 메소드가 deprecated 되었다고 합니다. 그 대신 queryForObject() 메소드를 사용할 수 있고 사용예제는 다음과 같습니다.

`int cnt = jdbcTemplate.queryForObject( "SELECT count(*) FROM users", Integer.class );`

**Comment by taxol1203** [comment]
이펙티브 자바에서 배운 `Integer.class`와 같은 형태를 부르는 명칭이 있었는데 기억이 나질 않네요. 좋은 정보 감사합니다!

**Comment by kjsu0209** [comment]
오랜만에 이펙티브 자바를 다시 봤네요 😄 
Item 33에 ```클래스 리터럴```이라는 개념이 나옵니다. 클래스 리터럴은 각 타입을 객체처럼 작동시키기 위해 ```Class<T>```로 제네릭하게 만든 것입니다.

(+ 복습)
컴파일타임 타입 정보와 런타임 타입 정보를 알아내기 위해 메서드들이 주고받는 클래스 리터럴을 ```타입 토큰```이라고 부릅니다.

[참고](https://javabookstudy.github.io/effective_java/EJ-Chapter5/)
