### ISSUE TITLE
[토비의 스프링] 5.2.3_트랜잭션 동기화 getConnection() 

### ISSUE THREAD

**Issue by jth2747** [JavaBookStudy/JavaBook#96]
p.362~363 트랜잭션 동기화 적용 부분에서,
getConnection()으로 연결하고 이후의 DAO 작업은 저 메소드에서 시작된 트랜잭션 안에서 진행된다 라는 게 잘 이해가 가지않네요.
p.363에 getConnection은 DS에서 Connection을 바로 가져오는것에 비해 트랜잭션 동기화에 사용하도록 저장소에 바인딩해준다고 적혀 있긴 한데 개념 그대로 이해하면 될까요???

**Comment by kjsu0209** [comment]
네 그대로 이해하면 될 것 같습니다.
connection은 dao에 접근할 때마다 새로 만드는 것이 아니라 한 번 만들고 재사용하니까 ```저장소에 바인딩```한다는 개념이 맞는 것 같네요.
